### PR TITLE
Changed to dark logo

### PR DESCRIPTION
**Pull request by radarhere**
Furo in https://github.com/python-pillow/Pillow/pull/6158
one
two

I think the dark Pillow logo looks better in the Furo theme. See also https://pillow-radarhere.readthedocs.io/en/furo/

three 
four

### CODE REVIEW

**Comment by hugovk** [comment]
It's possible to have different logos for each mode:

https://pradyunsg.me/furo/customisation/logo/#different-logos-for-light-and-dark-mode

Definitely the light mode needs updating, this looks better.

Which do you prefer for dark mode? Both look fine to me.

**Comment by radarhere** [comment]
I think the light logo looks better in dark mode, and the dark logo looks better in light mode.

**Comment by radarhere** [comment]
I've pushed a commit.

You're probably wondering why I've commented out `html_logo`. Here's what happens if you don't - https://pillow-radarhere.readthedocs.io/en/furo/. Two logos appear.

**Comment by hugovk** [comment]
I've enabled RTD build previews for my fork, closing and reopening to trigger.

**Comment by hugovk** [comment]
Take two...

**Review by hugovk — APPROVED** [review]
Looks good, thanks!

image
image

**Pull request merged**
